# Import Library

In [63]:
import pandas as pd
import numpy as np

import tensorflow as tf



from keras.models import Sequential
from keras.layers import Dense


from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D
from tensorflow.keras.layers import TextVectorization

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences #untuk proses padding

# Buat Objek Tokenizer + Parameternya

In [64]:
tokenizer = Tokenizer(num_words= 15, oov_token='-')

#Fungsi OOV adalah tidak menghilang setiap kata yg tidak memiliki token dan tidak hilang

# Buat Teks yg Ingin di Tokenisasi

In [65]:
teks = ['Saya suka programming',
        'Programming sangat menyenangkan!',
        'Machine Learning berbeda dengan pemrograman konvensional']

# Panggil Fungsi fit_on_text() pd Objek Tokenizer dg Mengisi Teks sebagai argumennya

In [66]:
tokenizer.fit_on_texts(teks)

# Ubah teks ke dalam sequence

In [67]:
sequences = tokenizer.texts_to_sequences(teks)

# Panggil Atribut word_index dari Objek Tokenizer

In [68]:
print(tokenizer.word_index)

{'-': 1, 'programming': 2, 'saya': 3, 'suka': 4, 'sangat': 5, 'menyenangkan': 6, 'machine': 7, 'learning': 8, 'berbeda': 9, 'dengan': 10, 'pemrograman': 11, 'konvensional': 12}


# Padding Agar Setiap Kalimat dalam Teks punya panjang yg sama

In [69]:
sequences_samapanjang = pad_sequences(sequences)

In [70]:
print(sequences_samapanjang)

#hasil menunjukkan setiap sequence sama panjang setelah dilakukan padding

[[ 0  0  0  3  4  2]
 [ 0  0  0  2  5  6]
 [ 7  8  9 10 11 12]]


# Mengisi nilai post

In [71]:
sequences_samapanjang = pad_sequences(sequences,
                                      padding='post',
                                      maxlen=5,
                                      truncating='post')

In [72]:
print(sequences_samapanjang)

[[ 3  4  2  0  0]
 [ 2  5  6  0  0]
 [ 7  8  9 10 11]]


# Pembuatan Model dg IMPLEMENTASI EMBEDDING (MENCARI KATA-KATA YG MIRIP)

In [73]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(250, 16, input_length=20),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Model Compile

In [74]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])